### ISSUE TITLE
Select doesnt work with HMR

### ISSUE THREAD

**Issue by montella1507** [ngrx-utils/ngrx-utils#77]
@Select() doesnt work with HMR after hot reload. Observable is NULL (works when manual assignment)

DOESNT work after HMR hot reload:
```
 @Select(data)
  data$: Observable<any>;
```

Works
```
 data$: Observable<any>;
 this.data$ = store.select(data);
```

i rly love your work, however if selecr doesnt work in HMR, it is for too  big price

**Comment by sandangel** [comment]
@montella1507 thanks for reporting this bug. Actually I'm planning to remove these decorators since it's not tree shakable and not recommended by the angular team. I think I already marked this as deprecated. I think I will remove them in next release (which upgrade to angular v9). Do you have any question?
